version: '3'


services:
  django:
    build:
      context: .
      dockerfile: ./Docker/local/django/Dockerfile
    image: doom_local_django
    container_name: doom_local_django
    volumes:
      - .:/django
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: /start

